apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kelomo2502/Advanced-GitOps-Techniques.git'
    targetRevision: main
    path: Advanced-GitOps-Techniques/blog_app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
